CREATE TABLE IF NOT EXISTS `user` (
    `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT 'サービス側で管理しているユーザー識別子',
    `username` VARCHAR(20) NOT NULL UNIQUE COMMENT 'ユーザー名',
    `user_handle` VARCHAR(36) NOT NULL UNIQUE COMMENT 'ユーザーハンドル (Web Authn 用のユーザー識別子, UUID)',
    
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
